### ISSUE TITLE
How to use with docker compose ?

### ISSUE THREAD

**Issue by yoyobee1** [DreamItGetIT/wait-for-mysql#1]
Hello, 

I just want to use this in docker compose, how to implement it ? Is it correct ?
my_wait:
  image: digit/wait-for-mysql
mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=mydb
    - MYSQL_USER=dbuser
    - MYSQL_PASSWORD=123456
  links:
    - my_wait:waitme

Thanks and Best Regards

**Comment by croman** [comment]
The way to use it without docker-compose would be like this:

```
docker run -d -p 3306:3306 --name db \
    -e MYSQL_ROOT_PASSWORD=root_password \
    -e MYSQL_USER=db_user \
    -e MYSQL_PASSWORD=password \
    -e MYSQL_DATABASE=my_db \
    library/mysql
docker run --rm --link db:mysql digit/wait-for-mysql
```

I think the docker-compose file should look something like this:

```
version: '2'

services:
  my_wait:
    image: digit/wait-for-mysql
    links:
      - db:mysql
  db:
    image: library/mysql
    container_name: db
    ports:
      - 3006:3006
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=my_db
```

I've read a few things about docker compose but I'm not currently using it so let me know if this works.
